
drop TABLE if exists `src.td_zmbr_mbr_card`;
CREATE EXTERNAL TABLE `src.td_zmbr_mbr_card`(
  `mbr_card_num1` string,
  `svc_mgmt_num` string,
  `mbr_card_num2` string,
  `mbr_st_cd` string,
  `mbr_typ_cd` string,
  `mbr_gr_cd` string,
  `card_isue_req_dt` string,
  `mbr_scrb_dt` string,
  `card_isue_dt` string,
  `card_term_dt` string,
  `imisu_yn` string,
  `sms_agree_yn` string,
  `ocb_accum_agree_yn` string,
  `svc_nominal_rel_cd` string,
  `fmly_cust_nm` string,
  `fmly_card_isue_dt` string,
  `fmly_card_isue_req_dt` string,
  `fmly_post_cd` string,
  `self_auth_yn` string,
  `op_org_id` string,
  `crtr_id` string,
  `cre_dtm` string,
  `audit_id` string,
  `audit_dtm` string,
  `mbr_scrb_stpl_snd_yn` string,
  `t_turpss_agr_yn` string,
  `mbr_func_use_yn` string,
  `t_turpss_scrb_stpl_snd_yn` string,
  `mms_agree_yn` string,
  `mbr_card_img_num` string,
  `mbr_gr_plus_yn` string,
  `mbr_ctz_ser_num` string,
  `mbr_ctz_num_pinf` string,
  `fmly_ctz_ser_num` string,
  `fmly_ctz_num_pinf` string,
  `mbr_card_img_req_cnt` string,
  `ctz_num_agree_yn` string,
  `mktg_agree_yn` string,
  `jncard_link_yn` string,
  `card_isue_typ_cd` string,
  `diy_yn` string,
  `email_newsl_agree_yn` string,
  `email_prod_agree_yn` string,
  `email_etc_agree_yn` string,
  `sms_mms_agree_yn` string,
  `tm_rcv_yn` string,
  `mms_ad_rcv_agree_dt` string,
  `oper_dt_hms` string,
  `del_flag` string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\u0002'
;

drop TABLE if exists `src.td_zpay_ap_req_spc`;
CREATE EXTERNAL TABLE `src.td_zpay_ap_req_spc`(
  `acnt_num` string,
  `ser_num` string,
  `req_dt` string,
  `bank_prt_yn` string,
  `tmth_drw_yn` string,
  `ctz_num_check_yn` string,
  `fst_drw_schd_dt` string,
  `fst_req_dt` string,
  `cust_num_idnt_cl_cd` string,
  `cmms_aply_yn` string,
  `card_eff_ym` string,
  `forgn_card_yn` string,
  `cms_cl_cd` string,
  `dpst_card_ownr_nm` string,
  `dpstr_rel_cd` string,
  `payer_num_cl_cd` string,
  `pay_mthd_cd` string,
  `bank_card_co_cd` string,
  `prchs_card_cd` string,
  `inst_cl_cd` string,
  `fin_kftc_op_dt` string,
  `cntc_num` string,
  `pay_cycl_cd` string,
  `auto_pay_chg_rsn_cd` string,
  `op_sale_org_id` string,
  `rep_svc_num` string,
  `auto_pay_rcv_cl_cd` string,
  `term_cl_cd` string,
  `term_drw_dt` string,
  `term_drw_err_cd` string,
  `cncl_dt` string,
  `auto_pay_req_cl_cd` string,
  `auto_pay_req_rslt_cd` string,
  `send_cl_cd` string,
  `rcv_chnl_cl_cd` string,
  `rcv_sale_org_id` string,
  `auth_rslt_cd` string,
  `auth_req_dt` string,
  `del_yn` string,
  `act_dt` string,
  `svc_cd` string,
  `idnt_num_cd` string,
  `fst_drw_dt` string,
  `req_opr_id` string,
  `sale_br_org_id` string,
  `dir_br_org_id` string,
  `agnt_nm` string,
  `agnt_cntc_num` string,
  `agnt_rel_cd` string,
  `cust_rel_cl_cd` string,
  `audit_id` string,
  `audit_dtm` string,
  `bar_cd_num` string,
  `drw_ts` string,
  `ctz_biz_ser_num` string,
  `ctz_biz_num_pinf` string,
  `bank_card_ser_num` string,
  `agnt_ctz_ser_num` string,
  `agnt_ctz_num_pinf` string,
  `edi_req_yn` string,
  `drwagr_prf_typ_cd` string,
  `drwagr_prf_key_val` string,
  `ap_req_dtm` string,
  `img_key_aply_cl_cd` string,
  `oper_dt_hms` string,
  `del_flag` string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\u0002'
;

drop TABLE if exists `src.td_zord_acnt`;
CREATE EXTERNAL TABLE `src.td_zord_acnt`(
  `acnt_num` string,
  `audit_id` string,
  `audit_dtm` string,
  `invr_nm` string,
  `acnt_typ_cd` string,
  `pay_mthd_cd` string,
  `inv_email_addr` string,
  `acnt_rgst_dt` string,
  `last_inv_dt` string,
  `inv_cycl_cd` string,
  `bill_isue_typ_cd` string,
  `sprat_pay_tax_bill_biz_num` string,
  `sprat_pay_bizr_nm` string,
  `bill_incld_yn` string,
  `cntc_num` string,
  `rep_cntrct_mgmt_num` string,
  `rep_svc_mgmt_num` string,
  `email_st_cd` string,
  `acnt_curnt_dt` string,
  `acnt_integ_yn` string,
  `addr_id` string,
  `bldblk_num` string,
  `bldunt_num` string,
  `assist_addr` string,
  `new_addr_yn` string,
  `integ_txt_addr_id` string,
  `pay_cycl_cd` string,
  `payer_num_cl_cd` string,
  `last_drw_dt` string,
  `scur_bill_yn` string,
  `vm_dload_yn` string,
  `co_cl_cd` string,
  `am_ddlv_chrg_sale_emp_id` string,
  `email_inv_dc_cl_cd` string,
  `bill_snd_cycl_cd` string,
  `inv_bank_prt_yn` string,
  `wsms_bill_snd_num` string,
  `wire_mbl_phon_dtl_isue_yn` string,
  `wire_dphon_dtl_isue_yn` string,
  `wire_ophon_dtl_isue_yn` string,
  `wsmbil_rcv_svc_mgmt_num` string,
  `mbl_phon_tc_dtl_incld_yn` string,
  `fin_inst_nm_prt_yn` string,
  `isct_bond_dlg_yn` string,
  `blind_exclsv_email_yn` string,
  `nreq_guid_sms_snd_yn` string,
  `incomm_bp_id` string,
  `ldong_cd` string,
  `admst_area_cd` string,
  `af_term_brws_rst_yn` string,
  `oper_dt_hms` string,
  `del_flag` string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\u0002'
;

drop table if exists src.td_zpay_card_pay;
CREATE EXTERNAL TABLE `src.td_zpay_card_pay`(
  `acnt_num` string,
  `op_dt` string,
  `pay_op_tm` string,
  `ser_num` string,
  `rep_svc_mgmt_num` string,
  `svc_cd` string,
  `svc_num` string,
  `acnt_svc_cl_cd` string,
  `card_op_cl_cd` string,
  `settl_way_cd` string,
  `cash_pay_amt` string,
  `card_cd` string,
  `card_eff_ym` string,
  `card_amt` string,
  `card_allot_mth_cnt` string,
  `scrbr_rel_cd` string,
  `dpst_card_ownr_nm` string,
  `foi_yn` string,
  `tmth_col_cl_cd` string,
  `uninv_yn` string,
  `auto_op_yn` string,
  `van_co_cl_cd` string,
  `op_sale_org_id` string,
  `deal_id` string,
  `card_proc_cd` string,
  `aprv_num` string,
  `settl_dt` string,
  `cmms_amt` string,
  `foi_allot_cmms_amt` string,
  `sacan_aprv_yn` string,
  `sacan_req_dt` string,
  `sacan_settl_dt` string,
  `card_err_cd` string,
  `audit_id` string,
  `audit_dtm` string,
  `card_co_inv_dt` string,
  `req_dtm` string,
  `rps_dtm` string,
  `ars_pay_path_cd` string,
  `card_ser_num` string,
  `card_co_cmms_amt` string,
  `card_co_foi_alt_cmms_amt` string,
  `card_prt_cncl_amt` string,
  `card_bamt` string,
  `ars_op_path_nm` string,
  `csr_id` string,
  `oper_dt_hms` string,
  `del_flag` string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\u0002'
;

drop TABLE if exists `src.td_zord_acnt_chg_hst`;
CREATE EXTERNAL TABLE `src.td_zord_acnt_chg_hst`(
  `acnt_num` string,
  `chg_dt` string,
  `acnt_chg_cd` string,
  `ser_num` string,
  `audit_id` string,
  `audit_dtm` string,
  `main_chg_cd` string,
  `acnt_chg_rsn_cd` string,
  `mktg_chg_typ_cd` string,
  `mktg_chg_rsn_cd` string,
  `chg_dtm` string,
  `cncl_dtm` string,
  `reqr_cl_cd` string,
  `reqr_nm` string,
  `reqr_cntc_num` string,
  `reqr_rel_cd` string,
  `reqr_ag_lgrp_ctz_num` string,
  `op_sale_org_id` string,
  `req_sale_org_id` string,
  `req_sale_br_org_id` string,
  `reqr_ctz_ser_num` string,
  `reqr_ctz_num_pinf` string,
  `op_memo_id` string,
  `sale_chnl_cl_cd` string,
  `bchg_itm1` string,
  `achg_itm1` string,
  `bchg_itm2` string,
  `achg_itm2` string,
  `bchg_itm3` string,
  `achg_itm3` string,
  `bchg_itm4` string,
  `achg_itm4` string,
  `bchg_itm5` string,
  `achg_itm5` string,
  `bchg_itm6` string,
  `achg_itm6` string,
  `bchg_itm7` string,
  `achg_itm7` string,
  `bchg_itm8` string,
  `achg_itm8` string,
  `bchg_itm9` string,
  `achg_itm9` string,
  `bchg_itm10` string,
  `achg_itm10` string,
  `bchg_itm11` string,
  `achg_itm11` string,
  `bchg_itm12` string,
  `achg_itm12` string,
  `bchg_itm13` string,
  `achg_itm13` string,
  `bchg_itm14` string,
  `achg_itm14` string,
  `bchg_itm15` string,
  `achg_itm15` string,
  `bchg_itm16` string,
  `achg_itm16` string,
  `bchg_itm17` string,
  `achg_itm17` string,
  `bchg_itm18` string,
  `achg_itm18` string,
  `bchg_itm19` string,
  `achg_itm19` string,
  `bchg_itm20` string,
  `achg_itm20` string,
  `bchg_itm21` string,
  `achg_itm21` string,
  `bchg_itm22` string,
  `achg_itm22` string,
  `bchg_itm23` string,
  `achg_itm23` string,
  `bchg_itm24` string,
  `achg_itm24` string,
  `bchg_itm25` string,
  `achg_itm25` string,
  `bchg_itm26` string,
  `achg_itm26` string,
  `bchg_itm27` string,
  `achg_itm27` string,
  `bchg_itm28` string,
  `achg_itm28` string,
  `bchg_itm29` string,
  `achg_itm29` string,
  `bchg_itm30` string,
  `achg_itm30` string,
  `bchg_itm31` string,
  `achg_itm31` string,
  `bchg_itm32` string,
  `achg_itm32` string,
  `bchg_itm33` string,
  `achg_itm33` string,
  `bchg_itm34` string,
  `achg_itm34` string,
  `bchg_itm35` string,
  `achg_itm35` string,
  `bchg_itm36` string,
  `achg_itm36` string,
  `bchg_itm37` string,
  `achg_itm37` string,
  `bchg_itm38` string,
  `achg_itm38` string,
  `bchg_itm39` string,
  `achg_itm39` string,
  `bchg_itm40` string,
  `achg_itm40` string,
  `bchg_itm41` string,
  `achg_itm41` string,
  `bchg_itm42` string,
  `achg_itm42` string,
  `bchg_itm43` string,
  `achg_itm43` string,
  `bchg_itm44` string,
  `achg_itm44` string,
  `bchg_itm45` string,
  `achg_itm45` string,
  `bchg_itm46` string,
  `achg_itm46` string,
  `bchg_itm47` string,
  `achg_itm47` string,
  `bchg_itm48` string,
  `achg_itm48` string,
  `bchg_itm49` string,
  `achg_itm49` string,
  `bchg_itm50` string,
  `achg_itm50` string,
  `oper_dt_hms` string,
  `del_flag` string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\u0002'
;

-- SRC.TD_ZPAY_CARD_PAY
INSERT INTO src.td_zpay_card_pay(rep_svc_mgmt_num, scrbr_rel_cd) VALUES ('1','031'), ('1','050'), ('2','010');

-- SRC.TD_ZORD_ACNT_CHG_HST
INSERT INTO src.td_zord_acnt_chg_hst(acnt_num, reqr_rel_cd) VALUES ('10','031'), ('11','050'), ('12','031');

-- SRC.TD_ZORD_ACNT
INSERT INTO src.td_zord_acnt(rep_svc_mgmt_num, acnt_num) VALUES ('3','10'), ('3','11'), ('4','12'), ('5','13'), ('6','14');

-- SRC.TD_ZPAY_AP_REQ_SPC
INSERT INTO src.td_zpay_ap_req_spc(acnt_num, dpstr_rel_cd) VALUES ('10','010'), ('11','050'), ('13','031');
INSERT INTO src.td_zpay_ap_req_spc(acnt_num, agnt_rel_cd)  VALUES ('14','050');

-- SRC.TD_ZMBR_MBR_CARD
INSERT INTO src.td_zmbr_mbr_card(svc_mgmt_num, svc_nominal_rel_cd, mbr_card_num1) VALUES ('7','031','1234567890'), ('8','050','1111');

-- DEMO.SVC_FMLY_REL(예상치)
-- SVC_MGMT_NUM   WEDD_YN   CHLD_EXIST_YN
--      1           Y           Y
--      2           #           #
--      3           Y           Y
--      4           Y           #
--      5           Y           #
--      6           #           Y
--      7           Y           #
--      8           #           #
